# Generated by Django 2.2.24 on 2021-11-26 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umnoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image_background',
            field=models.ImageField(blank=True, help_text='Please add only .PNG files for background images. This image will be used on Organization background image.', null=True, upload_to='org_background'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Please add only .PNG files for logo images. This logo will be used on Organization logo.', null=True, upload_to='org_logos'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Человеко-понятный уникальный идентификатор'),
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_background',
            field=models.ImageField(blank=True, help_text='Please add only .PNG files for background images. This image will be used on Project background image.', null=True, upload_to='project_background'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Please add only .PNG files for logo images. This logo will be used on Project logo.', max_length=255, null=True, upload_to='project_logos'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='umnoc.Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Человеко-понятный уникальный идентификатор'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationcourse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umnoc.Organization'),
        ),
    ]
